Description: Udagram app infraestructure

Parameters:
  EnvName:
    Description: Name of the environment. 
    Type: String
  BastionAccessIp:
    Description: Ip address for where bastion can be accessed
    Type: String
  BastionImageId:
    Description: AIM image for bastion pc
    Type: String
    Default: ami-003634241a8fcdec0
  SourceCodeS3Bucket:
    Description: S3 bucket with app source code
    Type: String

Resources:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: BastionSecurityGroup
      GroupDescription: Security group for network entry poing
      VpcId:
        Fn::ImportValue:
          !Sub ${EnvName}-MainVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref BastionAccessIp
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvName} bastion security group

  BastionServer:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: migue@pangea
      DisableApiTermination: false
      ImageId: !Ref BastionImageId
      InstanceType: t2.micro
      Monitoring: false
      IamInstanceProfile: !Ref AccessS3BucketInstanceProfile
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet: 
          - !Ref BastionSecurityGroup
        SubnetId: 
          Fn::ImportValue: !Sub ${EnvName}-PublicSubnetAid
      Tags:
        - Key: Name
          Value: !Sub ${EnvName} bastion

  MainAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MainAppSecurityGroup
      GroupDescription: !Sub ${EnvName} main app security group
      VpcId:
        Fn::ImportValue: !Sub ${EnvName}-MainVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref MainAppLBSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvName} main app servers security group

  MainAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: MainAppConfiguration2
      AssociatePublicIpAddress: false
      IamInstanceProfile: !Ref AccessS3BucketInstanceProfile
      ImageId: !Ref BastionImageId
      EbsOptimized: false
      InstanceMonitoring: false
      InstanceType: t2.micro
      KeyName: udagram-internal
      SecurityGroups:
        - !Ref MainAppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install apache2 -y
          apt-get install unzip -y
          systemctl start apache2.service
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          cd /var/www/html
          aws s3 cp s3://${SourceCodeS3Bucket}/site.zip site.zip
          unzip -o site.zip
          rm site.zip

  MainAppASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub ${EnvName}-PrivateSubnetAid
        - Fn::ImportValue: !Sub ${EnvName}-PrivateSubnetBid
      LaunchConfigurationName: 
        Ref: MainAppLaunchConfig
      MaxSize: 2
      MinSize: 2
      Tags:
        - Key: Name
          Value: !Sub ${EnvName} main app server
          PropagateAtLaunch: true
      TargetGroupARNs:
        - Ref: MainAppLBTargetGroup
  
  MainAppLBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MainAppLBSecurityGroup
      GroupDescription: !Sub ${EnvName} main app load balancer security group
      VpcId:
        Fn::ImportValue: !Sub ${EnvName}-MainVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  MainAppLBEgressRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !GetAtt MainAppLBSecurityGroup.GroupId 
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      DestinationSecurityGroupId: !Ref MainAppSecurityGroup

  MainAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SecurityGroups:
        - !Ref MainAppLBSecurityGroup
      Subnets:
        - Fn::ImportValue: !Sub ${EnvName}-PublicSubnetAid
        - Fn::ImportValue: !Sub ${EnvName}-PublicSubnetBid
  
  MainAppLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn:
        Ref: MainAppLB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: 
            Ref: MainAppLBTargetGroup

  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref MainAppLBTargetGroup
      Conditions:
      - Field: path-pattern
        Values: [/]
      ListenerArn: !Ref MainAppLBListener
      Priority: 1

  MainAppLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 3
      HealthyThresholdCount: 3
      # Matcher: 
      #   HttpCode: 200
      Name: !Sub ${EnvName}-main-app-lb-tg
      Port: 80
      Protocol: HTTP
      # Tags: 
      #   - Tag
      UnhealthyThresholdCount: 3
      VpcId: 
        Fn::ImportValue: !Sub ${EnvName}-MainVpcId


  AccessS3BucketInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: AccessS3BucketRole

  AccessS3BucketRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AccessS3BucketRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - 
         PolicyName: "access-s3-elements"
         PolicyDocument:
           Version: "2012-10-17"
           Statement:
              - 
                Effect: "Allow"
                Action: 
                  - s3:GetObject
                  - s3:ListBucket
                Resource: 
                  - !Sub arn:aws:s3:::${SourceCodeS3Bucket}
                  - !Sub arn:aws:s3:::${SourceCodeS3Bucket}/*